/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改



export const layouts: Record<string, () => Promise<any>> = {
"(base)": () => import("@/pages/(base)/layout.tsx"),
"(blank)": () => import("@/pages/(blank)/layout.tsx"),
"(blank)_login": () => import("@/pages/(blank)/login/layout.tsx"),
"root": () => import("@/pages/layout.tsx"),
};

export const pages: Record<string, () => Promise<any>> = {
"(base)_function": () => import("@/pages/(base)/function/index.tsx"),
"(base)_function_logistics": () => import("@/pages/(base)/function/logistics/index.tsx"),
"(base)_function_order": () => import("@/pages/(base)/function/order/index.tsx"),
"(base)_function_product": () => import("@/pages/(base)/function/product/index.tsx"),
"(base)_home": () => import("@/pages/(base)/home/index.tsx"),
"(blank)_login-out": () => import("@/pages/(blank)/login-out/index.tsx"),
"(blank)_login_code-login": () => import("@/pages/(blank)/login/code-login/index.tsx"),
"(blank)_login": () => import("@/pages/(blank)/login/index.tsx"),
"(blank)_login_register": () => import("@/pages/(blank)/login/register/index.tsx"),
"(blank)_login_reset-pwd": () => import("@/pages/(blank)/login/reset-pwd/index.tsx"),
"root": () => import("@/pages/index.tsx"),
};

export const errors: Record<string, () => Promise<any>> = {
"root": () => import("@/pages/error.tsx"),
};