/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

//这里只能修改 handle 并且路由组作为布局路由组件 是不能有handle的

import type { ElegantConstRoute } from '@soybean-react/vite-plugin-react-router';

export const generatedRoutes: ElegantConstRoute[] = [
  {
    matchedFiles: ['root', '/src/pages/index.tsx', '/src/pages/loading.tsx', 'root'],
    name: 'root',
    path: '/',
    handle: { i18nKey: 'route.root', title: 'root', constant: true },
    children: [
      {
        matchedFiles: ['(base)', null, null, null],
        name: '(base)',
        children: [
          {
            matchedFiles: [null, '/src/pages/(base)/function/index.tsx', null, null],
            name: '(base)_function',
            path: '/function',
            handle: { i18nKey: 'route.(base)_function', title: '(base)_function' },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/function/category/index.tsx', null, null],
                name: '(base)_function_category',
                path: '/function/category',
                handle: { i18nKey: 'route.(base)_function_category', title: '(base)_function_category' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/coupon/index.tsx', null, null],
                name: '(base)_function_coupon',
                path: '/function/coupon',
                handle: { i18nKey: 'route.(base)_function_coupon', title: '(base)_function_coupon' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/logistics/index.tsx', null, null],
                name: '(base)_function_logistics',
                path: '/function/logistics',
                handle: { i18nKey: 'route.(base)_function_logistics', title: '(base)_function_logistics' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/order/index.tsx', null, null],
                name: '(base)_function_order',
                path: '/function/order',
                handle: { i18nKey: 'route.(base)_function_order', title: '(base)_function_order' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/product/index.tsx', null, null],
                name: '(base)_function_product',
                path: '/function/product',
                handle: { i18nKey: 'route.(base)_function_product', title: '(base)_function_product' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/promotion/index.tsx', null, null],
                name: '(base)_function_promotion',
                path: '/function/promotion',
                handle: { i18nKey: 'route.(base)_function_promotion', title: '(base)_function_promotion' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/refund/index.tsx', null, null],
                name: '(base)_function_refund',
                path: '/function/refund',
                handle: { i18nKey: 'route.(base)_function_refund', title: '(base)_function_refund' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/review/index.tsx', null, null],
                name: '(base)_function_review',
                path: '/function/review',
                handle: { i18nKey: 'route.(base)_function_review', title: '(base)_function_review' }
              },
              {
                matchedFiles: [null, null, null, null],
                name: '(base)_function_system',
                path: '/function/system',
                handle: { i18nKey: 'route.(base)_function_system', title: '(base)_function_system' },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/function/system/role/index.tsx', null, null],
                    name: '(base)_function_system_role',
                    path: '/function/system/role',
                    handle: { i18nKey: 'route.(base)_function_system_role', title: '(base)_function_system_role' }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/function/system/user/index.tsx', null, null],
                    name: '(base)_function_system_user',
                    path: '/function/system/user',
                    handle: { i18nKey: 'route.(base)_function_system_user', title: '(base)_function_system_user' }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/home/index.tsx', null, null],
            name: '(base)_home',
            path: '/home',
            handle: { i18nKey: 'route.(base)_home', icon: 'mdi:monitor-dashboard', order: 1, title: 'home' }
          }
        ],
        path: null
      },
      {
        matchedFiles: ['(blank)', null, null, null],
        name: '(blank)',
        children: [
          {
            matchedFiles: ['(blank)_login', '/src/pages/(blank)/login/index.tsx', null, null],
            name: '(blank)_login',
            path: '/login',
            handle: { i18nKey: 'route.(blank)_login', title: '(blank)_login', constant: true },
            children: [
              {
                matchedFiles: [null, '/src/pages/(blank)/login/code-login/index.tsx', null, null],
                name: '(blank)_login_code-login',
                path: '/login/code-login',
                handle: { i18nKey: 'route.(blank)_login_code-login', title: '(blank)_login_code-login', constant: true }
              },
              {
                matchedFiles: [null, '/src/pages/(blank)/login/register/index.tsx', null, null],
                name: '(blank)_login_register',
                path: '/login/register',
                handle: { i18nKey: 'route.(blank)_login_register', title: '(blank)_login_register', constant: true }
              },
              {
                matchedFiles: [null, '/src/pages/(blank)/login/reset-pwd/index.tsx', null, null],
                name: '(blank)_login_reset-pwd',
                path: '/login/reset-pwd',
                handle: { i18nKey: 'route.(blank)_login_reset-pwd', title: '(blank)_login_reset-pwd', constant: true }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(blank)/login-out/index.tsx', null, null],
            name: '(blank)_login-out',
            path: '/login-out',
            handle: { i18nKey: 'route.(blank)_login-out', title: '(blank)_login-out', constant: true }
          }
        ],
        path: null
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: 'notFound',
        path: '*',
        handle: { i18nKey: 'route.notFound', title: 'notFound', constant: true }
      }
    ]
  }
];
